### ISSUE TITLE
app crashes in compare/periods

### ISSUE THREAD

**Issue by sandropons** [tmunzer/AnalyticsRef#8]
Hello,

when i go to compare-> periods, the app crashes, unfortunately i don't have a clue...

Here the exit error:
`STATUS: 400
HEADERS: {"content-type":"text/html","date":"Fri, 04 Mar 2016 11:51:46 GMT","server":"nginx","content-length":"166","connection":"keep-alive"}

undefined:1
&lt;html&gt;
^
SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/home/sandro/AnalyticsRef-master/bin/aerohive/api/req.js:36:37)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
`

I hope you can have a look at it or give me a clue eventually.

Regards,
Sandro

**Comment by tmunzer** [comment]
Hi Sandro,

Thanks.
For this error, it seems the ACS replied with a HTML content, instead of a JSON one.

Can you try to pull the latests commits? I added some control and UI error messages?

Thanks,
—
Thomas Munzer
